In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:99% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:18pt;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

<b><font size="7" color="red">ch11. 데이터프레임과 시리즈(Pandas)</font></b>
- pip install pandas
# 1절 판다스 패키지
- 데이터 분석을 위해 반드시 알아야 할 패키지. 넘파이를 기반으로 하며,
  다른 많은 라이브러리와 잘 통합되도록 설계
  
- 2차원 구조를 갖는 데이터프레임, 1차원 구조를 갖는 시리즈를 제공

- 판다스 장점 : 
    * 데이터프레임생성, 파일io, 레이블링, 부분데이터 추출, 
    * 크기변경(행이나 열 삽입, 삭제), 데이터 분할, 병합, 데이터구조변경, 결측치 처리
        
- https://pypi.python.org/pypi/pandas (package index)
- http://pandas.pydata.org/pandas-docs/stable/api.html (API reference)

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

In [4]:
pd.read_json?

In [8]:
data = pd.read_json('data/ch09_member1.json', 
                    encoding='cp949') # 기본 encoding은 utf-8
display(data)
print(type(data))

name  Age        Email Address
0  홍길동   30  hg@hong.com      서울
1  박길동   20  pg@hong.com      부산
2  신길동   25  sg@hong.com      대전

<class 'pandas.core.frame.DataFrame'>


In [9]:
member4 = pd.read_csv('data/ch09_member4.csv') # 기본 encoding=utf-8
member4

name  Age        Email Address
0  신길동   30  sg@hong.com      서울
1  홍길동   20  ho@hong.com      수원
2  마길동   25  ma@hong.com      안양

In [12]:
member1 = pd.read_csv('data/ch09_member1.csv',
                     header=None,
                     names=['name','age','email','address'])
member1

name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

# 2절 데이터프레임 만들기
## 2.1 딕셔너리 리스트를 이용해서 데이터 프레임 만들기

In [14]:
d = [{'kor':100, 'mat':95}, {'kor':90, 'mat':99}]
df = pd.DataFrame(data=d)
df

kor  mat
0  100   95
1   90   99

In [15]:
df.to_dict() # 데이터프레임을 딕셔너리로 

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [18]:
df.to_numpy() # 데이터프레임을 넘파이배열
df.values    # 데이터프레임을 넘파이배열

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [21]:
df.dtypes # 열의 타입

kor    int64
mat    int64
dtype: object

In [22]:
df.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [23]:
df['kor'].dtype

dtype('int64')

In [28]:
# 타입변경(열마다)
import numpy as np
df['kor'].astype(np.float64)
df['kor'] = df['kor'].astype('float64') # kor열의 타입을 float64로

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     2 non-null      float64
 1   mat     2 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes


In [34]:
d = [{'kor':100.0, 'mat':95}, {'kor':90, 'mat':99}, {'kor':92, 'eng':99}]
df = pd.DataFrame(data=d)
df

kor   mat   eng
0  100.0  95.0   NaN
1   90.0  99.0   NaN
2   92.0   NaN  99.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   kor     3 non-null      float64
 1   mat     2 non-null      float64
 2   eng     1 non-null      float64
dtypes: float64(3)
memory usage: 200.0 bytes


In [32]:
type(np.nan) # np.nan결측치

float

In [37]:
df['kor'] = df['kor'].astype('int32')
df

kor   mat   eng
0  100  95.0   NaN
1   90  99.0   NaN
2   92   NaN  99.0

In [39]:
# 결측치는 int로 형변환 불가(결측치를 대체값으로 치환 후 변환)
#df['mat'] = df['mat'].astype('int32')

## 2.2 리스트를 이용해서 데이터프레임 만들기

In [41]:
kor = [100,90,95,90,65]
mat = [99,100,95,98,94]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df.head(2) # 상위 2행만

kor  mat
0  100   99
1   90  100

In [42]:
np.c_[kor, mat]

array([[100,  99],
       [ 90, 100],
       [ 95,  95],
       [ 90,  98],
       [ 65,  94]])

In [47]:
df = pd.DataFrame(data=np.c_[kor, mat], columns=['국어','수학'])
df

국어   수학
0  100   99
1   90  100
2   95   95
3   90   98
4   65   94

In [48]:
df.shape

(5, 2)

In [51]:
l = [['트렌드 코리아2026', '김난도', 18000, 10],
     ['사탄탱고', '라슬로', 17820, 10],
     ['미술관 여행자', '카미유주노', 29700, 10]]
df = pd.DataFrame(l, columns=['책이름','저자','가격','할인율'])
df

책이름     저자     가격  할인율
0  트렌드 코리아2026    김난도  18000   10
1         사탄탱고    라슬로  17820   10
2      미술관 여행자  카미유주노  29700   10

In [ ]:
# %ls : ipython 매직명령어
# !dir : 쉘명령어

In [58]:
%ls "D:\ai\downloads\shareData\상가정보"

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: B2C0-28EF

 D:\ai\downloads\shareData\상가정보 디렉터리

2025-10-12  오후 03:33    <DIR>          .
2025-10-12  오후 03:33    <DIR>          ..
2025-04-27  오후 11:07             1,011 [필독]파일열람방법.txt
2025-04-27  오후 11:07        61,227,944 소상공인시장진흥공단_상가(상권)정보_강원_202503.csv
2025-04-27  오후 11:07       356,572,082 소상공인시장진흥공단_상가(상권)정보_경기_202503.csv
2025-04-27  오후 11:07        93,472,559 소상공인시장진흥공단_상가(상권)정보_경남_202503.csv
2025-04-27  오후 11:07        76,425,275 소상공인시장진흥공단_상가(상권)정보_경북_202503.csv
2025-04-27  오후 11:07        40,070,868 소상공인시장진흥공단_상가(상권)정보_광주_202503.csv
2025-04-27  오후 11:07        61,715,005 소상공인시장진흥공단_상가(상권)정보_대구_202503.csv
2025-04-27  오후 11:07        41,491,092 소상공인시장진흥공단_상가(상권)정보_대전_202503.csv
2025-04-27  오후 11:07        84,550,600 소상공인시장진흥공단_상가(상권)정보_부산_202503.csv
2025-04-27  오후 11:07       294,549,483 소상공인시장진흥공단_상가(상권)정보_서울_202503.csv
2025-04-27  오후 11:07         9,303,432 소상공인시장진흥공단_상가(상권)정보_세종_202503.csv
2025-04-27  오후 11:07        28,457,489 소상공인시장진흥공단_상가(상권

In [60]:
df = pd.read_csv(r'D:\ai\downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_서울_202503.csv',
                encoding='utf-8', sep=',', # 기본값 생략가능
                nrows=70) # 처음70행만 가져오기
df.shape

(70, 39)

In [61]:
df.head(1) # 상위1행만

상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명  \
0  MA010120220800000033  부동산임대김은숙  NaN        I2       음식      I212    비알코올    

  상권업종소분류코드 상권업종소분류명 표준산업분류코드  ...                     건물관리번호  건물명  \
0    I21201       카페   I56229  ...  1111014000100280021026727  NaN   

                 도로명주소   구우편번호 신우편번호  동정보 층정보  호정보         경도        위도  
0  서울특별시 종로구 삼청로 122-1  110230  3053  NaN NaN  NaN  126.98184  37.58625  

[1 rows x 39 columns]

In [64]:
# 판다스 디스플레이 옵션
pd.options.display.max_columns = 39 # 39열까지 display가능. 기본값은 20
pd.options.display.max_rows = 70    # 70행까지 display가능. 기본값은 60

In [66]:
df.head(1)

상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명  \
0  MA010120220800000033  부동산임대김은숙  NaN        I2       음식      I212    비알코올    

  상권업종소분류코드 상권업종소분류명 표준산업분류코드       표준산업분류명  시도코드    시도명  시군구코드 시군구명  \
0    I21201       카페   I56229  기타 비알코올 음료점업    11  서울특별시  11110  종로구   

      행정동코드 행정동명       법정동코드 법정동명                 지번코드  대지구분코드 대지구분명  지번본번지  \
0  11110540  삼청동  1111014000  삼청동  1111014000100280021       1    대지     28   

   지번부번지                 지번주소         도로명코드            도로명  건물본번지  건물부번지  \
0   21.0  서울특별시 종로구 삼청동 28-21  111103100007  서울특별시 종로구 삼청로    122    1.0   

                      건물관리번호  건물명                도로명주소   구우편번호  신우편번호  동정보  \
0  1111014000100280021026727  NaN  서울특별시 종로구 삼청로 122-1  110230   3053  NaN   

   층정보  호정보         경도        위도  
0  NaN  NaN  126.98184  37.58625

In [67]:
df.head(1).T

0
상가업소번호          MA010120220800000033
상호명                         부동산임대김은숙
지점명                              NaN
상권업종대분류코드                         I2
상권업종대분류명                          음식
상권업종중분류코드                       I212
상권업종중분류명                       비알코올 
상권업종소분류코드                     I21201
상권업종소분류명                          카페
표준산업분류코드                      I56229
표준산업분류명                 기타 비알코올 음료점업
시도코드                              11
시도명                            서울특별시
시군구코드                          11110
시군구명                             종로구
행정동코드                       11110540
행정동명                             삼청동
법정동코드                     1111014000
법정동명                             삼청동
지번코드             1111014000100280021
대지구분코드                             1
대지구분명                             대지
지번본번지                             28
지번부번지                           21.0
지번주소             서울특별시 종로구 삼청동 28-21
도로명코드                   111103100007
도로명                    서울특별시 종로구 삼청로
건물본번지                            122
건물부번지                            1.0
건물관리번호     1111014000100280021026727
건물명                              NaN
도로명주소            서울특별시 종로구 삼청로 122-1
구우편번호                         110230
신우편번호                           3053
동정보                              NaN
층정보                              NaN
호정보                              NaN
경도                         126.98184
위도                          37.58625

## 2.3 read_csv

In [70]:
# help(pd.read_csv)
#pd.read_csv() # 함수 안에서 shift+tab+tab
pd.read_csv?

In [72]:
# (1) CSV 파일 불러오기(기본값)
member = pd.read_csv('data/ch11_member.csv',
                    #, encoding='utf-8', sep=',', comment주석처리X
                    )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [79]:
# 문자형으로 읽어들인 Birth를 datetime형으로
# 형변환 : astype('int64'), astype('datetime64' : 비추)
#         to_datetime()함수
# member['Birth'].astype('datetime64') 비추
member['Birth'] = pd.to_datetime(member['Birth'])
member.head(1)

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [80]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int64         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 368.0+ bytes


In [81]:
import numpy as np
member['Age'] = member['Age'].astype(np.int16)
member.dtypes

Name               object
Age                 int16
Email              object
Address            object
Birth      datetime64[ns]
dtype: object

In [84]:
# (2) 특정행을 제외하고 csv 파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv',
                    encoding='cp949',
                    skiprows=[1,6]) # 1,6번째 행 제외하고 읽어오기(시작은 1부터)
member

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [86]:
# (3) 상위몇행만 sep문자는 ,아닌 csv파일 읽어오기
member = pd.read_csv('data/ch11_membersep.csv',
                    nrows=5, # 상위 5행만
                    sep='|')
member

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [91]:
# (4) 주석(#)제외, datetime형 필드를 지정하여 csv 파일 읽어오기
member = pd.read_csv('data/ch11_membertab.csv',
                    sep='\t',     # 구분자 설정
                    comment='#',  # 주석제외
                    parse_dates=['Birth']) # datetime64형으로 읽어올 필드 지정
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     5 non-null      object        
 1   Age      5 non-null      int64         
 2   Email    5 non-null      object        
 3   Address  5 non-null      object        
 4   Birth    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 328.0+ bytes


## 2.4 패키지에서 가져오기 : iris 데이터
- iris 가져오기 방법1 : sklearn(머신러닝 패키지)
- iris 가져오기 방법2 : statsmodels (R 데이터)
- iris 가져오기 방법3 : seaborn(시각화패키지)
### 2.4.1 iris 방법1 : sklearn
- sklearn.datasets 모듈 데이터(iris)를 데이터 프레임으로 변환

In [100]:
from sklearn import datasets # 머신러닝을 공부하기 위한 학습 데이터셋 제공
# sklearn 패키지에서 제공되는 데이터셋은 딕셔너리형식으로 제공
iris = datasets.load_iris()
print(type(iris)) # Bunch타입(딕셔너리를 상속받은 타입) 딕셔너리처럼 동작
# print(iris.DESCR) # iris 데이터 셋의 설명
print(iris.keys())

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [102]:
iris.data # 독립변수
iris['data'][:3] # 상위 3행

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [103]:
# 데이터프레임의 열이름(비추)
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [106]:
# 데이터프레임의 열이름(강추)
[col[:-5].replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [109]:
iris.target # ML/DL 학습시 타겟변수(종속변수)
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [111]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [113]:
iris.target_names[iris.target] # 데이터프레임에 쓸 타겟변수(가장 오른쪽 열)

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [117]:
# 독립변수
data = iris.data
# 종속변수
target = iris.target_names[iris.target].reshape(-1, 1)
print(data[:3], target[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] [['setosa']
 ['setosa']
 ['setosa']]


In [119]:
print('독립변수 shape :', data.shape)
print('타겟변수 shape :', target.shape)

독립변수 shape : (150, 4)
타겟변수 shape : (150, 1)


In [123]:
# 1. 독립변수와 종속변수를 stack한후 데이터 프레임으로
df = pd.DataFrame(np.hstack((data, target)),
                 columns=iris.feature_names + ['species'])
df.head(1)

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0               5.1              3.5               1.4              0.2   

  species  
0  setosa

In [134]:
#df.sepal length (cm)
# df['sepal length (cm)'] 
df.columns = [col[:-5].replace(' ', '_') for col in iris.feature_names] + ['species']
df.head(1)

sepal_length sepal_width petal_length petal_width species
0          5.1         3.5          1.4         0.2  setosa

In [135]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: object

In [137]:
# 2. 독립변수, 종속변수를 따로 데이터프레임으로 생성-> 두 데이터프엠을 연결
X = pd.DataFrame(iris.data, 
                 columns=[col[:-5].replace(' ', '_') for col in iris.feature_names])
X.head(1)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [138]:
y = pd.DataFrame(iris.target_names[iris.target], columns=['species'])
y.head(1)

species
0  setosa

In [142]:
print('X의 shape :', X.shape)
print('y의 shape :', y.shape)
print('X의 index :', X.index)
print('y의 index :', y.index)

X의 shape : (150, 4)
y의 shape : (150, 1)
X의 index : RangeIndex(start=0, stop=150, step=1)
y의 index : RangeIndex(start=0, stop=150, step=1)


In [145]:
iris_df = pd.concat( [X, y], axis=1 ) # 두개의 데이터프레임을 열로 연결
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


### 2.4.2 iris 방법1 : statsmodels

In [3]:
# R 패키지의 기본 데이터 가져오기
from statsmodels.api import datasets
iris_dataset = datasets.get_rdataset('iris',
                                    package='datasets',
                                    cache=True) # 한번 다운로드한 데이터를 pc에 저장
iris_dataset

<class 'statsmodels.datasets.utils.Dataset'>

In [5]:
iris = iris_dataset.data
iris.head() # 상위5행

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
iris['Sepal.Length']
# iris.Sepal.Length # 열이름에 .이 있으면 iris.Sepal.Length 접근불가

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

In [13]:
iris.columns = [col.replace('.','_').lower() for col in iris.columns]
iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

### 2.4.3 iris 방법3 : seaborn

In [14]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [18]:
# 데이터프레임을 파일로 출력 (4k)
iris.to_csv('data/ch11_iris.csv',
           sep=',', encoding='utf-8', # 기본값
           index=False) # 행이름이 생략되서 파일 출력

In [22]:
iris.to_csv('data/ch11_iris.csv.gz', # 889B
           index=False,
           compression='infer') # 파일 확장자에 맞게 압축

In [23]:
import pandas as pd
# read_iris = pd.read_csv('data/ch11_iris.csv')
read_iris = pd.read_csv('data/ch11_iris.csv.gz', compression='infer')
read_iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

# 3절 이름(열, 행) 지정하기
## 3.1 열이름 지정하기

In [27]:
member = pd.read_csv('data/ch11_member.csv', 
                    comment='#',
                    parse_dates=['Birth'])
member.head(1)

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [30]:
member.columns = ['이름','나이','메일','주소','생일']
member

이름  나이             메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

## 3.2 행이름 지정

In [29]:
member.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
member.index = range(11, 16)
member

이름  나이             메일       주소         생일
11  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
12  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
13  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
14  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
15  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [32]:
member.index = ['동','서','남','북','중']
member

이름  나이             메일       주소         생일
동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [36]:
# member['이름']['동'] 비추
member.loc['동', '이름'] # 행과 열이름으로 부분 데이터 조회 : loc

'홍길동'

In [41]:
# index를 이름열로 (실행결과가 출력되서 나오면 return될뿐, member는 안 바뀜)
# member를 수정하려면 (1)할당 (2) inplace 매개변수에 True(기본값 False)
member1 = member.set_index('이름')
member1.head(1)

나이             메일       주소         생일
이름                                        
홍길동  20  hong@hong.com  서울시 강동구 1999-01-01

In [42]:
member.set_index('이름', inplace=True)

In [43]:
member

나이             메일       주소         생일
이름                                        
홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
홍길서  30   seo@hong.com   서울시 중구 1999-12-01
홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [44]:
member.index

Index(['홍길동', '홍길서', '홍길남', '홍길북', '홍길중'], dtype='object', name='이름')

In [46]:
# 인덱스를 컬럼으로 편입시키기
member.reset_index(inplace=True)

In [49]:
member.index = [0, 1, 2, 0, 1]
member

이름  나이             메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
0  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
1  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [56]:
# 기존의 index를 새로운 열에 편입시키지 않고 제거한 후, 새로운 숫자 index로 초기화
# member.index = range(len(member))
member = member.reset_index(drop=True)
member

이름  나이             메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [59]:
# datetime열에서 날짜 및 시간에 관련된 정보를 추출 : 시리즈.dt
member['생일'].dt.year

0    1999
1    1999
2    1999
3    1999
4    1999
Name: 생일, dtype: int64

In [60]:
member['생일'].dt.month

0     1
1    12
2    11
3     5
4     1
Name: 생일, dtype: int64

In [61]:
member['생일'].dt.weekday # 0:월, 1:화, ... 5:토, 6:일

0    4
1    2
2    0
3    5
4    5
Name: 생일, dtype: int64

## 3.3 레벨이름 지정하기

In [62]:
member

이름  나이             메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [65]:
print(member.columns)
print(member.columns.name)

Index(['이름', '나이', '메일', '주소', '생일'], dtype='object')
None


In [66]:
member.columns.name = '정보'
member

정보   이름  나이             메일       주소         생일
0   홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1   홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2   홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3   홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4   홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [67]:
member.columns = [['기본정보','기본정보','기본정보','추가정보','추가정보'],
                  ['이름','나이','메일','주소','생일']]
member.columns.names = ['대분류','소분류']
member

대분류 기본정보                        추가정보           
소분류   이름  나이             메일       주소         생일
0    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [68]:
member.index = [['좌우','좌우','상하','상하','상하'],
                ['동','서','남','북','중']]
member.index.names = ['레벨1','레벨2']
member

대분류     기본정보                        추가정보           
소분류       이름  나이             메일       주소         생일
레벨1 레벨2                                            
좌우  동    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
    서    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
상하  남    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
    북    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
    중    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [74]:
member.loc[('상하','중'), '기본정보']

소분류
이름             홍길중
나이              23
메일    mid@hong.com
Name: (상하, 중), dtype: object

In [70]:
member.loc[('상하','북'),('기본정보','이름')]

'홍길북'

In [72]:
member.loc['상하', '기본정보']

소분류   이름  나이            메일
레벨2                       
남    홍길남  21  nam@hong.com
북    홍길북  22  buk@hong.com
중    홍길중  23  mid@hong.com

# 4절 부분 데이터 조회

In [76]:
member = pd.read_csv('data/ch11_member.csv', 
                     comment='#',
                    parse_dates=['Birth'])
member

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 4.1 단일 열 조회

In [78]:
member['Name']
member.Name

0    홍길동
1    홍길서
2    홍길남
3    홍길북
4    홍길중
Name: Name, dtype: object

In [80]:
# member[0] # 행이름으로 []로 조회할 경우 에러

In [81]:
member[['Name','Address']]

Name  Address
0  홍길동  서울시 강동구
1  홍길서   서울시 중구
2  홍길남  서울시 강동구
3  홍길북  서울시 관악구
4  홍길중   부산시 중구

## 4.2 loc을 이용한 조회
- df.loc[행이름, 열이름] : 행이름, 열이름으로 조회
    * 행이름과 열이름자리에 슬라이싱 from:to : from부터 to까지(to 포함)
    * 행이름과 여이름자리에 리스트

In [87]:
member.loc[0:2]
member.loc[0:2,]
member.loc[0:2, :] 
member.loc[0:2, ...] # 모든 열을 다 출력할 경우 열 생략가능

Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [89]:
member.index = ['동','서','남','북','중']
member.loc['동':'남']

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [90]:
member.loc['동':'남', 'Name':'Address'] #동~남행, Name~Address열까지

Name  Age          Email  Address
동  홍길동   20  hong@hong.com  서울시 강동구
서  홍길서   30   seo@hong.com   서울시 중구
남  홍길남   21   nam@hong.com  서울시 강동구

In [91]:
# 동,남행, Name, Email, Address 열
member.loc[['동','남'], ['Name','Email','Address']]

Name          Email  Address
동  홍길동  hong@hong.com  서울시 강동구
남  홍길남   nam@hong.com  서울시 강동구

In [95]:
member.loc[:, 'Name']

동    홍길동
서    홍길서
남    홍길남
북    홍길북
중    홍길중
Name: Name, dtype: object

## 4.3 iloc을 이용한 조회
- df.iloc[행순번, 열순번] : 행순번, 열순번으로 조회
    * 행순번과 열순번자리에 슬라이싱 from:to:by - from부터 to 앞까지 by씩(to 미포함)
    * 행순번과 열순번자리에 리스트

In [96]:
member

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [97]:
# 동(0)행부터 남(2)행까지 모든 열
member.iloc[0:3]
member.iloc[0:3, ]
member.iloc[0:3, :]
member.iloc[0:3, ...]

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [99]:
# 0번째 행
type(member.iloc[0])

pandas.core.series.Series

In [100]:
# 동행부터 남행까지 Name(0)열부터 Address(3)열까지
member.iloc[0:3, 0:4]
member.iloc[0:3, 0:-1]

Name  Age          Email  Address
동  홍길동   20  hong@hong.com  서울시 강동구
서  홍길서   30   seo@hong.com   서울시 중구
남  홍길남   21   nam@hong.com  서울시 강동구

In [101]:
# 짝수번째 행의 마지막 열을 제회하고 출력
member.iloc[::2, :-1]

Name  Age          Email  Address
동  홍길동   20  hong@hong.com  서울시 강동구
남  홍길남   21   nam@hong.com  서울시 강동구
중  홍길중   23   mid@hong.com   부산시 중구

In [102]:
# 마지막행부터 처음행까지 꺼꾸로 출력
member.iloc[::-1]

Name  Age          Email  Address      Birth
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [103]:
# 동(0)행과 남(2)행, Name(0)열, Email(2)열, Address(3)열
member.iloc[[0,2], [0,2,3]]

Name          Email  Address
동  홍길동  hong@hong.com  서울시 강동구
남  홍길남   nam@hong.com  서울시 강동구

In [107]:
# Name(0)열
member.iloc[:, 0]
member.iloc[..., 0]

동    홍길동
서    홍길서
남    홍길남
북    홍길북
중    홍길중
Name: Name, dtype: object

## 4.4 조건으로 조회하기

In [108]:
member

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [109]:
member['Name']=='홍길남'

동    False
서    False
남     True
북    False
중    False
Name: Name, dtype: bool

In [111]:
# Name이 홍길남이 행을 모두
member[member['Name']=='홍길남']
member.loc[member['Name']=='홍길남']
member.loc[ [False, False, True, False, False] ]

Name  Age         Email  Address      Birth
남  홍길남   21  nam@hong.com  서울시 강동구 1999-11-01

In [112]:
# Name이 홍길남의 이름과 나이 Email
member.loc[member['Name']=='홍길남', 'Name':'Email']

Name  Age         Email
남  홍길남   21  nam@hong.com

In [113]:
# Name이 홍길남의 이름과 Email
member.loc[member['Name']=='홍길남', ['Name','Email'] ]

Name         Email
남  홍길남  nam@hong.com

In [118]:
# 23세 이상 데이터 조회(모든 열)
member.loc[member['Age']>=23]
member.loc[member['Age']>=23, ]
member.loc[member['Age']>=23, :]
member.loc[member['Age']>=23, ...]
member[member['Age']>=23]

Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [119]:
# 23세 이상의 Name, Age, Email
member.loc[member['Age']>=23, 'Name':'Email']

Name  Age         Email
서  홍길서   30  seo@hong.com
중  홍길중   23  mid@hong.com

In [120]:
# 23세 이상의 Name, Age, Address
member.loc[member['Age']>=23, ['Name','Age','Address'] ]

Name  Age Address
서  홍길서   30  서울시 중구
중  홍길중   23  부산시 중구

In [121]:
# ~ : 반대
member[~(member['Age']>=23)]

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01

In [124]:
address = '서울시 관악구'
print('서울시로 시작하는지 여부 :', address.startswith('서울시'))
print('중구가 포함 여부 :', address.find('중구')!=-1)

서울시로 시작하는지 여부 : True
중구가 포함 여부 : False


In [128]:
# member['Address'].startswith('서울시')

※ 시리즈에 문자함수를 쓰기 위해 참조(pdf29page) :
https://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling 

In [129]:
# 서울시로 시작하는 데이터
member['Address'].str.startswith('서울시')

동     True
서     True
남     True
북     True
중    False
Name: Address, dtype: bool

In [130]:
member[member['Address'].str.startswith('서울시')]

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01

In [132]:
# Address에 중구를 포함하는 데이터(방법1)
member[member['Address'].str.find('중구')!=-1]

Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [134]:
# Address에 중구를 포함하는 데이터(방법2)
member[member['Address'].str.contains('중구')]

Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [137]:
# 시리즈.isin([])
# 이름이 홍길동이거나 홍길남이 데이터
member.loc[member['Name'].isin(['홍길동','홍길남'])]
member[member['Name'].isin(['홍길동','홍길남'])]

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [138]:
# 이름이 홍길동이거나 홍길남이 데이터의 이름, 주소, 생일
member.loc[member['Name'].isin(['홍길동','홍길남']), ['Name','Address','Birth']]

Name  Address      Birth
동  홍길동  서울시 강동구 1999-01-01
남  홍길남  서울시 강동구 1999-11-01

In [141]:
# 2000년 이전에 태어난 데이터
member[member['Birth'].dt.year < 2000]

Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

※ 데이터 프레임의 부분 데이터 조회방법
- df[열이름] : 특정열 조회
- df[조건] : 조건에 맞는 모든 행 조회
- df.loc[행이름, 열이름] 
    - 행이름, 열이름 자리에 슬라이싱, 리스트
    - 열이름 생략시 모든 열
    - 행이름 자리에 조건
- df.iloc[행순번, 열순번]
    - 행이름, 열이름 자리에 슬라이싱, 리스트
    - 열이름 생략시 모든 열